spring:
  datasource:
    url: jdbc:mysql://localhost:3306/soft_test_db?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: testmaker
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

mybatis:
  type-aliases-package: com.softtest.softtest.entity
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.softtest.softtest.dao: DEBUG